
---
title:
output:
  html_document:
    df_print: paged
---

<h1 style="text-align:center">MISSION</h1>

<p>
The objective of the Interest Group is to:

* Serve as the primary group at ASA for furthering methodological and substantive activity in statistics and data science related to aging research.

* Partner with other organizations to further such research.

* Partner with other interest groups, and with sections and chapters, of the American Statistical Association, to further such activity.

* Gather statisticians, data scientists, and other aging researchers to provide a platform for sharing expertise and experiences.

* Sponsor educational activities consistent with the interests of the members of the Interest Group.

* Membership in the Interest Group is open to anyone interested in statistical and data science and their applications in aging research. There are no dues, but the Interest Group accepts contributions.

* The annual business meeting of the Interest Group shall be held in connection with the annual Joint Statistical Meetings and shall be announced in advance.

</p>

<h1 style="text-align:center">CHARTER</h1>
<h1 style="text-align:center">
```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(downloadthis)

download_file(
  path = "./charter/sdsa_charter.pdf",
  button_label = "Download SDSA charter",
  button_type = "success",
  has_icon = TRUE,
  icon = "fa fa-save",
  self_contained = FALSE
)

```
</h1>

