---
---

<h1> Webinars </h1>







```{r, echo = FALSE, message = FALSE, warning = FALSE }
library(tidyverse)
library(knitr)
library(kableExtra)
```


## Fall 2025 - Spring 2026 SDSA Webinars

```{r, echo = FALSE, message = FALSE, warning = FALSE }
dt_url <- c(
  "https://youtu.be/5haNC1nBoDs",
  "https://amstat.zoom.us/webinar/register/WN_-QrTGG2tS7yKXREkiJn6-Q",
  "https://youtu.be/HAsSrpZX_Xc",
  "https://amstat.zoom.us/webinar/register/WN_t_OqPrVXRueS6ng72bhVaw"
            )

tib = tibble(
  `Date` = c(
    "9/25/2025",
    "10/23/2025",
    "11/19/2025",
    "2/17/2026"
  ),
    `Time` = c(
    "4-5pm ET/3-4pm CT/2-3pm MT/1-2pm PT",
    "noon-1pm ET/11am-noon CT/10-11am MT/9-10am PT",
    "noon-1pm ET/11am-noon CT/10-11am MT/9-10am PT",
    "2-3pm ET/1-2pm CT/noon-1pm MT/11am-noon PT"),
  `Speaker` = c(
    "Paola Sebastiani, PhD, Professor of Medicine, Tufts University School of Medicine",
    "Liam Messin, Deputy Editor for Nature Medicine & Sebastien Thuault Chief Editor of Nature Aging",
    "Lihua Li, PhD, MS, Associate Professor at Icahn School of Medicine at Mount Sinai",
    "Selena Wang, PhD, Assistant Professor, Indiana University School of Medicine"
  ),
  `Title` = c(
    "Metabolite Signatures of Chronological Age, Aging, Survival and Longevity",
    "Aging research at Nature Aging and Nature Medicine",
    "Integrating propensity score weighting methods and population-based surveys for cancer and aging research",
    "Implementing Network Science in Generative Statistical Processes"
  ),
  `Registration/talk links` = c(
     "YouTube",
    "Registration",
    "YouTube",
    "Registration"
    )
)

kable(tib[nrow(tib):1,], row.names = FALSE) %>%
  kable_styling(bootstrap_options = "striped",font_size = 15, repeat_header_method = "replace") %>%
  column_spec(1, width = ".5cm") %>%
  column_spec(2, width = "2cm") %>%
  column_spec(3, width = "4cm") %>%
  column_spec(4, width = "5cm")%>%
  column_spec(5, width = ".5cm",link = dt_url[nrow(tib):1])
```


## ARISE – Fall 2025 Webinar Series

<details>
  <summary>Detailed information for titles and speakers</summary>
<embed src="files/ARISE - Schedule Fall 2025_updated.pdf#toolbar=0" width="600px" height="800px"
    scrolling="auto"/>
</details>
<br>

```{r, echo = FALSE, message = FALSE, warning = FALSE }
dt_url <- c("https://amstat.zoom.us/j/84186505606?pwd=pMZ4DV1KkIbK3Jd0G6EnBUsAFebtiD.1",
            "https://amstat.zoom.us/j/84186505606?pwd=pMZ4DV1KkIbK3Jd0G6EnBUsAFebtiD.1",
            "https://amstat.zoom.us/j/84186505606?pwd=pMZ4DV1KkIbK3Jd0G6EnBUsAFebtiD.1",
            "https://amstat.zoom.us/j/84186505606?pwd=pMZ4DV1KkIbK3Jd0G6EnBUsAFebtiD.1")

tib = tibble(
  `Date` = c(
    "8/27/2025",
    "9/8/2025",
    "10/29/2025",
    "11/3/2025"
  ),
    `Time` = c(
    "1-2pm ET/12-1pm CT/11am-12pm MT/10-11am PT",
    "12-1pm ET/11am-12pm CT;10-11am MT/9-10am PT",
    "1-2pm ET/12-1pm CT/11am-12pm MT/10-11am PT",
    "12-1pm ET/11am-12pm CT;10-11am MT/9-10am PT"
  ),
  `Speaker` = c(
    "Tianying Wang, PhD; Owen Li, PhD Student; Molly Ehrig, MS",
    "Pulkit Khandelwal, PhD; Boyi Hu, PhD Candidate; Julia Gallini, PhD Candidate",
    "Xuexin Yu, PhD; Margaret Gacheru, PhD; Matthew R. Scott, PhD Candidate",
    "Jiachen Chen, PhD Candidate; Alessandra Pescina, MS; Deependra Kaji Thapa, PhD"
     ),
  `Title` = c("","","",""
     ),
  `Registration/talk links` = c(
    "Zoom",
    "Zoom",
    "Zoom",
    "Zoom"
   )
)

kable(tib[nrow(tib):1,], row.names = FALSE) %>%
  kable_styling(bootstrap_options = "striped",font_size = 15, repeat_header_method = "replace") %>%
  column_spec(1, width = ".5cm") %>%
  column_spec(2, width = "2cm") %>%
  column_spec(3, width = "4cm") %>%
  column_spec(4, width = "5cm")%>%
  column_spec(5, width = ".5cm",link = dt_url[nrow(tib):1])
```


## Fall 2024 - Spring 2025 SDSA Webinars

```{r, echo = FALSE, message = FALSE, warning = FALSE }
dt_url <- c("https://youtu.be/-jJwOjizPtU",
            "https://www.youtube.com/watch?v=dw74CQJZ3v0",
            "https://www.youtube.com/watch?v=rWAeVmjyorQ",
            "https://youtu.be/N578BcxJ0yM",
            "https://youtu.be/xoRSS12b0mU",
            "https://youtu.be/XroGLWF0EzI")

tib = tibble(
  `Date` = c(
    "9/30/2024",
    "10/29/2024",
    "01/13/2025",
    "02/27/2025",
    "03/26/2025",
    "05/08/2025"
  ),
    `Time` = c(
    "1-2pm ET/12-1pm CT/11am-12pm MT/10-11am PT",
    "2-3pm ET/1-2pm CT;12-1pm MT/11am-12pm PT",
    "1-2pm ET/12-1pm CT/11am-12pm MT/10-11am PT",
    "1-2pm ET/12-1pm CT/11am-12pm MT/10am-11am PT",
    "1-2pm ET/12-1pm CT/11am-12pm MT/10am-11am PT",
    "1-2pm ET/12-1pm CT/11am-12pm MT/10am-11am PT"
  ),
  `Speaker` = c(
    "Wenbo Wu, PhD, NYU",
    "Yates Coley, PhD, Kaiser Permanente Washington Health Research Institute & the University of Washington",
    "Roee Gutman, PhD, Professor, Department of Biostatistics, Brown University",
    "Heather Shappell, PhD, Wake Forest University School of Medicine",
    "Carly Bobak, MS, PhD & James O’Malley, MS, PhD, Dartmouth Geisel School of Medicine",
    "John Boscardin, PhD, Departments of Medicine and Epidemiology & Biostatistics, University of California, San Francisco"
    ),
  `Title` = c(
    "Data Science-Powered Provider Profiling for Equitable Quality Care in Alzheimer's and Dementia",
    "The electronic health record Risk of Alzheimer’s and Dementia Assessment Rule (eRADAR): External validation and embedded pragmatic clinical trial in two real-world healthcare systems",
    "Novel Bayesian Record Linkage Methods with Application to Medicare Beneficiaries",
    "Dynamic Brain Networks in Obesity and Weight Loss in Older Adults",
    "Gaming the System: Evaluating Spillover in a Video Game Intervention for Advanced Care Planning using Physician Social Networks",
    "Building better prognostic models: balancing accuracy, interpretability, and usability in the care of older adults"
    ),
  `Registration/talk links` = c(
    "Youtube",
    "Youtube",
    "Youtube",
    "Youtube",
    "Youtube",
    "Youtube"
   )
)

kable(tib[nrow(tib):1,], row.names = FALSE) %>%
  kable_styling(bootstrap_options = "striped",font_size = 15, repeat_header_method = "replace") %>%
  column_spec(1, width = ".5cm") %>%
  column_spec(2, width = "2cm") %>%
  column_spec(3, width = "4cm") %>%
  column_spec(4, width = "5cm")%>%
  column_spec(5, width = ".5cm",link = dt_url[nrow(tib):1])
```

